version: "3.9"
services:
      candidat:
            build: .\candidat
            image: candid4twin4
            container_name: candidat
            ports:
             - "8088:8088"
            environment: 
             - eureka.client.service-url.default-zone=http://discovery:8761/eureka
            depends_on: 
            - eureka
 


      job:
            build: .\Job
            image: job4twin4
            restart: unless-stopped
            container_name: job
            ports:
                  - "8087:8087"
            environment:
             - eureka.client.service-url.default-zone=http://discovery:8761/eureka
             - spring.datasource.url=jdbc:mysql://db-mysql:3306/job?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
             - spring.datasource.username=root
             - spring.datasource.password=root
            depends_on: 
             - eureka
             - db-mysql




      eureka:
       build: .\EurekaDiscovery
       image: eureka
       container_name: Eureka
       hostname: discovery
       ports:
            - "8761:8761"



      db-mysql:
            image: mysql:latest
            container_name: db-mysql 
            environment:
             - MYSQL_ROOT_PASSWORD=root  #indisponsable pour la conteneurisation
        #- MYSQL_DATABASE=job
            ports:
            - "3306:3306"
            restart: unless-stopped